name: tetraconnect
description: 4 in a row with 4 players

publish_to: 'none'

version: 1.0.1+5

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Launcher
  icons_launcher: ^2.1.6
  # flutter_app_name: ^0.1.1
  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_auth: ^4.15.3
  firebase_messaging: ^14.7.9
  firebase_analytics: ^10.7.4
  # App state
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  # Notifications
  overlay_support: ^2.1.0
  # Localisation
  intl: ^0.18.1
  # Profanity
  profanity_filter: ^2.0.0
  # Version info
  package_info_plus: ^5.0.1
  # File picking
  images_picker: ^1.2.11
  file_picker: ^6.1.1
  image_picker: ^0.8.7+4
  # Color picking
  flutter_colorpicker: ^1.0.3
  random_color: ^1.0.6-nullsafety
  # Statistics
  pie_chart: ^5.3.2
  fine_bar_chart: ^0.0.3
  # Permissions
  permission_handler: ^11.1.0
  # Http calls & downloads
  dio: ^5.3.3
  # Notifications
  flutter_local_notifications: ^10.0.0-dev.1
  # Play sound
  audioplayers: ^5.2.0
  # URL launcher
  url_launcher: ^6.3.0

icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true

# flutter_app_name:
  # name: "TetraConnect"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/circle.png
    - assets/square.png
    - assets/triangle.png
    - assets/cross.png
    - assets/sent_comment.wav
    - assets/gravity.gif
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Regular.ttf
flutter_intl:
  enabled: true
