name: tetraconnect
description: 4 in a row with 4 players

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Launcher
  icons_launcher: ^2.0.0
  flutter_app_name: ^0.1.1
  # Firebase
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.2
  firebase_storage: ^11.1.1
  firebase_auth: ^4.4.2
  firebase_messaging: ^14.4.1
  firebase_analytics: ^10.3.0
  # App state
  shared_preferences: ^2.1.0
  provider: ^6.0.5
  # Notifications
  overlay_support: ^2.1.0
  # Localisation
  intl: ^0.17.0
  # Profanity
  profanity_filter: ^2.0.0
  # Version info
  package_info_plus: ^3.1.2
  # File picking
  images_picker: ^1.2.11
  file_picker: ^5.2.9
  image_picker: ^0.8.7+4
  # Color picking
  flutter_colorpicker: ^1.0.3
  random_color: ^1.0.6-nullsafety
  # Statistics
  pie_chart: ^5.3.2
  fine_bar_chart: ^0.0.3


icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true

flutter_app_name:
  name: "TetraConnect"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/circle.png
    - assets/square.png
    - assets/triangle.png
    - assets/cross.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Regular.ttf
flutter_intl:
  enabled: true
