// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_8NorMVXjXUyi45K2KVKPNw7DP17Js_8',
    appId: '1:821629462628:web:1c0ff4ef254d059b185771',
    messagingSenderId: '821629462628',
    projectId: 'tetraconnect',
    authDomain: 'tetraconnect.firebaseapp.com',
    storageBucket: 'tetraconnect.appspot.com',
    measurementId: 'G-PC2P4XPQ4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQkfkqeLcJ8jC9EFtxxf_MkmuHNlPdlQQ',
    appId: '1:821629462628:android:9193d1fdc7bbcbb8185771',
    messagingSenderId: '821629462628',
    projectId: 'tetraconnect',
    storageBucket: 'tetraconnect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0fHhKGeldJv-nZ2qi4zvBNG12U_9raPw',
    appId: '1:821629462628:ios:57b5d39dcb25c0a0185771',
    messagingSenderId: '821629462628',
    projectId: 'tetraconnect',
    storageBucket: 'tetraconnect.appspot.com',
    iosClientId: '821629462628-5ecucu409vocirkl1hb5j1jdq0n3habd.apps.googleusercontent.com',
    iosBundleId: 'app.web.tetraconnect',
  );
}
